### ISSUE TITLE
"Please correct errors below"

### ISSUE THREAD

**Issue by djpeach** [mdn/django-locallibrary-tutorial#36] opened 2018-12-20 23:25 UTC
After adding inline forms, I noticed that I was not able to use them or even save my Books anymore. I am getting an error at the top that says "Please correct errors below". After some meddling, I found it was due to my UUID id field that is my primary key was read_only. I made it a readonly field because I didn't think it made sense to be able to edit this. However, when it is made readonly, the form registers it as an error (with not error list) and does not let the Parent element or the Child instance be saved. I know this is not where this can be fixed, but I don't think we should use UUID as the pk when this is an issue.

**Comment by hamishwillee** [comment] 2018-12-20 23:42
Hi Daniel,

The UUID is intended to be used as the primary key and that should be possible. From an example point of view this is not a bug - the code as supplied in this repo works and is sane.

I can look at your code in the new year if you can add it to a repo somewhere.

**Comment by djpeach** [comment] 2018-12-20 23:48
@hamishwillee My code is located here: https://github.com/djpeach/Django-Projects/tree/master/local_library

I can and am using the UUID as the primary key. Where should I go to report an issue of the field preventing the saving of the Parent element when it is read_only?

**Comment by hamishwillee** [comment] 2018-12-21 00:17
I'm not sure - perhaps the Django project - https://github.com/django/django

**Comment by hamishwillee** [comment] 2019-02-04 11:19
I'm closing this. It is a Django rather than example issue.

**Closed by hamishwillee** 2019-02-04 11:19 UTC
